/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempconverter.vista;

import tempconverter.modelo.ModeloTempConverter;

/**
 *
 * @author garciparedes
 */
public class VistaTempConverter extends javax.swing.JFrame {

    private ModeloTempConverter mModelo;
    private ControladorTempConverter mControlador;
    /**
     * Creates new form VistaTempConverter
     */
    public VistaTempConverter() {
        initComponents();
        mModelo = new ModeloTempConverter();
        mControlador = new ControladorTempConverter(this, mModelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDegrees = new javax.swing.JTextField();
        jTextFieldFahrenheit = new javax.swing.JTextField();
        jLabelFahrenheit = new javax.swing.JLabel();
        jLabelDegrees = new javax.swing.JLabel();
        JButtonConvert = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFahrenheit.setText("Fahrenheit:");

        jLabelDegrees.setText("Degrees:");

        JButtonConvert.setText("Convert");
        JButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonConvertActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDegrees, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFahrenheit, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFahrenheit)
                            .addComponent(jTextFieldDegrees)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JButtonConvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(jButtonExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDegrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDegrees))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFahrenheit)
                    .addComponent(jTextFieldFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonConvert)
                    .addComponent(jButtonExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonConvertActionPerformed
        mControlador.convert();
    }//GEN-LAST:event_JButtonConvertActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        mControlador.exit();
    }//GEN-LAST:event_jButtonExitActionPerformed

    public void updateFahrenheit(){
        jTextFieldFahrenheit.setText(Double.toString(mModelo.getFahrenheit()));
    }
    
    public double getCelsius(){
        return Double.parseDouble(jTextFieldDegrees.getText());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonConvert;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelDegrees;
    private javax.swing.JLabel jLabelFahrenheit;
    private javax.swing.JTextField jTextFieldDegrees;
    private javax.swing.JTextField jTextFieldFahrenheit;
    // End of variables declaration//GEN-END:variables
}
